recovery_behaviors: [{name: conservative_clear, type: ClearCostmapRecovery}, {name: aggressive_clear, type: ClearCostmapRecovery}]

conservative_clear:
  reset_distance: 3.0

aggressive_clear:
  reset_distance: 1.84

