NavfnROS:
 allow_unknown: false
#Independent settings for the planner's costmap
global_costmap: 
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 0.0
  static_map: true
  rolling_window: false
